import localFont from "next/font/local";
import "./globals.css";

const darkforce = localFont({
  src: "../font/dark-force.ttf",
  variable: "--font-darkforce",
});

const masaFont = localFont({
  src: "../font/masa-font.ttf",
  variable: "--font-masafont",
});

export const metadata = {
  title: "Unicorn Art Space",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${darkforce.variable} ${masaFont.variable}`}>
        {children}
      </body>
    </html>
  );
}
